#!/bin/sh

# 系统初始化配置

uci batch <<'EOF'
set system.@system[0].hostname='ImmortalWrt-N100'
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'

set network.lan.ipaddr='192.168.10.2'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.10.1'
set network.lan.dns='127.0.0.1 223.5.5.5 119.29.29.29'

set dhcp.lan.ignore='1'

set uhttpd.main.redirect_https='0'
set uhttpd.main.listen_http='0.0.0.0:80'

set firewall.@defaults[0].flow_offloading='1'
set firewall.@defaults[0].flow_offloading_hw='1'

set ttyd.@ttyd[0].interface='@lan'
EOF

uci commit

# 启用服务
/etc/init.d/ttyd enable || true
/etc/init.d/adguardhome enable || true
/etc/init.d/mosdns enable || true

rm -f /tmp/luci-indexcache
exit 0
